### ISSUE TITLE
After killing process and run node.js program again bus throws error

### ISSUE THREAD

**Issue by Kamil93** [capriza/node-busmq#18]
Windows 8.1 64bit, redis 2.8.2104 64 bit

After killing process that using node-busmq and rerunning it, bus throws error (if we will rerun it quickly, after some time it doesn't appear)

D:\project\node_modules\busmq\node_modules\redis\index.js:602
                throw err;
                ^

TypeError: Cannot read property 'hash' of undefined
    at Bus._script (D:\project\node_modules\busmq\lib\bus.js:158:28)
    at Queue.consume (D:\project\node_modules\busmq\lib\queue.js:620:40)
    at Queue.<anonymous> (D:\project\node_modules\busmq\lib\queue.js:602:15)
    at Queue.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Queue.emit (events.js:166:7)
    at D:\project\node_modules\busmq\lib\queue.js:110:11
    at D:\project\node_modules\busmq\lib\queue.js:238:11
    at D:\project\node_modules\busmq\lib\queue.js:268:13
    at arguments.(anonymous function) (D:\project\node_modules\busmq\lib\connection.js:198:18)

**Comment by fujifish** [comment]
Can you elaborate on why you closed?

**Comment by Kamil93** [comment]
It is all good. I didn't wait for online event.

**Comment by fujifish** [comment]
ok, thanks.
