### ISSUE TITLE
Firefox - NS_ERROR_SOCKET_CREATE_FAILED

### ISSUE THREAD

**Issue by tlenex** [capriza/node-busmq#43]
My sentry caught this error for firefox users:
```
NS_ERROR_SOCKET_CREATE_FAILED: null
  at ws(/api/lib/busmq.min.js:9:20794)
  at [60]</</WSMux.prototype._openWebsocket(/api/lib/busmq.min.js:10:30625)
  at WSMux(/api/lib/busmq.min.js:10:30438)
  at [61]</</WSPool.prototype._add(/api/lib/busmq.min.js:11:3599)
  at [61]</</WSPool/<(/api/lib/busmq.min.js:11:3258)
  at WSPool(/api/lib/busmq.min.js:11:3157)
  at [52]</</Bus.prototype._options(/api/lib/busmq.min.js:9:23364)
  at Bus(/api/lib/busmq.min.js:9:22634)
  at create(/api/lib/busmq.min.js:9:30878)
  at BusClient(/api/lib/busmq.min.js:11:5600)
  at [62]</module.exports(/api/lib/busmq.min.js:11:6368)
  at u(/scripts/scripts.ff8cbf955f58988ccc07209100738a2f.js:4:12010)
  at oa.Callbacks/j(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:2:7464)
  at oa.Callbacks/k.fireWith(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:2:8240)
  at d(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:3:12194)
  at .send/c(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:3:18093)
  at oa.event.dispatch(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:2:18828)
  at oa.event.add/q.handle(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:2:16882)
  at d(/scripts/vendor.c903ec96afe9be60b6139452f937f599.js:30:6863)
```

more info on same error in socket.io: https://github.com/socketio/engine.io-client/issues/474

**Comment by fujifish** [comment]
Fixed in version 1.6.2.
Thank you!
